[run]
init_cmds = [
  ["go", "build", "-o", "./bin/snmpcollector", "./pkg/"],
	["./bin/snmpcollector"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/pkg",
	"$WORKDIR/conf",
]
watch_exts = [".go", ".ini", ".toml", ".html"]
build_delay = 1500
cmds = [
  ["go", "build", "-o", "./bin/snmpcollector", "./pkg/"],
	["./bin/snmpcollector"]
]
